# Service for the EverShop app
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-evershop
spec:
  type: NodePort
  selector:
    app: evershop
  ports:
    - port: 3000
      targetPort: {{ .Values.evershop.containerPort }}
      nodePort: {{ .Values.evershop.nodePort }}

---
# Deployment for the EverShop app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-evershop
spec:
  replicas: {{ .Values.evershop.replicaCount }}         # Number of pod replicas
  selector:
    matchLabels:
      app: evershop
  template:
    metadata:
      labels:
        app: evershop
    spec:
      containers:
        - name: evershop
          image: "{{ .Values.evershop.image.repository }}:{{ .Values.evershop.image.tag }}"  # Docker image to use
          ports:
            - containerPort: {{ .Values.evershop.containerPort }}    # Port exposed inside container
          env:
            - name: DB_HOST
              value: "{{ .Release.Name }}-postgres"
            - name: DB_PORT
              value: "{{ .Values.postgres.port }}"
            - name: DB_USER
              value: "{{ .Values.postgres.user }}"
            - name: DB_PASSWORD
              value: "{{ .Values.postgres.password }}"
            - name: DB_NAME
              value: "{{ .Values.postgres.dbName }}"                    