controller:
  JCasC:
    enabled: true
    configScripts:
      kubernetes-cloud: |
        jenkins:
          clouds:
          - kubernetes:
              name: "minikube-cloud"
              serverUrl: "https://kubernetes.default.svc"
              namespace: "jenkins"
              jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
              connectTimeout: 5
              readTimeout: 15
              templates:
                - name: docker-agent
                  label: docker
                  containers:
                    - name: jnlp
                      image: jenkins/inbound-agent:latest
                      tty: true
                    - name: dind
                      image: docker:24.0.7-dind
                      securityContext:
                        privileged: true
                      env:
                        - name: DOCKER_HOST
                          value: tcp://localhost:2375
                      tty: true
                  volumes:
                    - name: docker-sock
                      emptyDir: {}

  admin:
    username: admin
    password: admin

  # Service exposure
  serviceType: NodePort
  service:
    ports:
      http: 8080
      jnlp: 50000

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - docker-workflow:latest
    - blueocean:latest
    - credentials-binding:latest

persistence:
  enabled: true
  storageClass: standard
  size: 10Gi
  path: /mnt/data/jenkins-home   # Map to Windows folder e.g. C:\minikube-data\jenkins-home

agent:
  enabled: true

serviceAccount:
  create: true
  name: "jenkins"

rbac:
  create: true
  readSecrets: true
  rules:
    - apiGroups: [""]
      resources: ["pods", "pods/log", "secrets"]
      verbs: ["get", "list", "watch", "create", "delete", "update"]
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["get", "list", "watch", "create", "update", "patch"]
    - apiGroups: [""]
      resources: ["services"]
      verbs: ["get", "list", "create", "update"]
    - apiGroups: ["batch"]
      resources: ["jobs"]
      verbs: ["get", "list", "create", "delete"]
    - apiGroups: [""]
      resources: ["persistentvolumeclaims"]
      verbs: ["get", "list", "create", "delete"]
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "list", "create", "update"]
