controller:
  JCasC:
    enabled: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Welcome to Jenkins on Minikube!"
      kubernetes-cloud: |
        jenkins:
          clouds:
          - kubernetes:
              name: "minikube-cloud"
              serverUrl: "https://kubernetes.default.svc"
              namespace: "default"
              jenkinsUrl: "http://jenkins.default.svc.cluster.local:8080"
              connectTimeout: 5
              readTimeout: 15
  service:
    ports:
      jnlp: 50000
  admin:
    username: admin
    password: admin
  serviceType: NodePort
  servicePort: 8081

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - docker-workflow:latest
    - blueocean:latest
    - credentials-binding:latest

persistence:
  enabled: true
  storageClass: standard
  size: 10Gi

agent:
  enabled: true
  podTemplates:
    docker: |
      - name: docker
        label: docker
        image: docker:24.0.7-dind
        privileged: true
        ttyEnabled: true
        resourceRequestCpu: "500m"
        resourceLimitCpu: "1000m"
        resourceRequestMemory: "512Mi"
        resourceLimitMemory: "1024Mi"

serviceAccount:
  create: true
  name: "jenkins"
  annotations: {}
rbac:
  create: true
  readSecrets: true
  rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]